name: Build and upload
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - run: npm install
      - run: npm update many-js
      - run: npm run build
      - name: 'Upload build'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build