name: Build And Test
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - run: npm install
      - run: npm run build
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - run: npm ci
      - run: npm run test -- --coverage
      - name: 'Upload coverage report'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage
          retention-days: 7