name: Build And Test
on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.14.0'
      - run: npm install
      - run: npm run build
      - run: npm run test